# _config.yml

# サイトの基本設定（SEO的にも軽く反映される）
title: minimalmine
description: minimal notes
baseurl: "" # サブドメインなので空でOK
url: "https://minimalmine.github.io"

# Markdownの変換エンジン指定
markdown: kramdown

theme: minima

# Google AnalyticsのトラッキングID（使うならここに入れてもOK）


# その他（必要なら追記できる）
plugins:
  - jekyll-sitemap
